// <auto-generated />
namespace Grant.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RecordBookFiles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RecordBookFiles));
        
        string IMigrationMetadata.Id
        {
            get { return "201509271953271_RecordBookFiles"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
