// <auto-generated />
namespace Grant.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class GrantEventFullInfo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GrantEventFullInfo));
        
        string IMigrationMetadata.Id
        {
            get { return "201509252033271_GrantEventFullInfo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
