// <auto-generated />
namespace Grant.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class GrantAttachments : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GrantAttachments));
        
        string IMigrationMetadata.Id
        {
            get { return "201509181643179_GrantAttachments"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
