// <auto-generated />
namespace Grant.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PersonalInfoMoreScans : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PersonalInfoMoreScans));
        
        string IMigrationMetadata.Id
        {
            get { return "201603181752570_PersonalInfoMoreScans"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
